{"errors":[{"id":null,"links":null,"status":"500","code":"500-Cse-Internal-Server-Exception","title":"CSE run failed","detail":"CSE run failed; nested exception is java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.io.IOException: java.lang.InterruptedException: interrupted; nested exception is java.lang.RuntimeException: java.io.IOException: java.lang.InterruptedException: interrupted; nested exception is java.io.IOException: java.lang.InterruptedException: interrupted; nested exception is java.lang.InterruptedException: interrupted","source":null,"meta":null}]}